# NumPy ndarray 개요
- NumPy (Numerical Python)는 Python에서 수치 계산을 위해 사용되는 핵심 라이브러리
- NumPy는 고성능의 다차원 배열 객체와 이러한 배열 작업을 위한 도구를 제공

**Numpy의 주요 기능:**
1. **다차원 배열**: NumPy의 핵심 기능은 N차원 배열 객체인 ndarray로, 동일한 유형의 항목을 가진 그리드를 나타내며, 각 항목은 배열의 차원에 의해 인덱싱 가능.
2. **배열 연산**: NumPy는 배열 간 산술 연산 함수도 함께 제공하며 이는 Python의 기본 연산보다 훨씬 빠르고 메모리를 효율적으로 사용함.
3. **수학 함수**: NumPy는 mathematical 함수를 제공하여 배열에 대한 연산을 쉽게 수행할 수 있음.
4. **선형대수 연산**: NumPy는 선형 대수 연산, 푸리에 변환 등 다양한 선형대수 연산을 지원.
5. 통합 기능: NumPy는 C, C++, Fortran으로 작성된 코드를 통합하는 도구 등을 제공함.

NumPy는 데이터 분석, 머신러닝, 과학 계산 등 다양한 분야에서 사용되며, Pandas, Matplotlib, Scikit-learn 등의 Python 데이터 과학 라이브러리의 기반이 됨

In [ ]:
import numpy as np

In [ ]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

In [ ]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

In [ ]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

In [ ]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

In [ ]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

# ndarray를 편리하게 생성하기 - arange, zeros, ones

### 참고 링크
https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy-arange

https://numpy.org/doc/stable/reference/generated/numpy.zeros.html

https://numpy.org/doc/stable/reference/generated/numpy.ones.html

In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

In [ ]:
sequence_array2 = np.arange(start=1, stop=10, step=3)
print(sequence_array2)
print(sequence_array2.dtype, sequence_array2.shape)

In [ ]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

# Reshape

In [ ]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

In [ ]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

# ***NumPy ndarray PRACTICE***

In [ ]:
array1 = np.arange(8)

''' PRACTICE

1. 1차원 array1 3차원 array3d 변환

[output]
array3d shape: (2, 2, 2)

2. 3차원 array3d 2차원 array2d 변환

[output]
array2d shape: (8, 1)

3. 1차원 array1를 2차원 array2d 변환

[output]
array2d shape: (4, 2)
'''

# Indexing
* 단일값 추출

In [ ]:
# 1에서 부터 9 까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

In [ ]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

* Slicing

In [ ]:
array1 = np.arange(start=1, stop=10)
print(array1)
array3 = array1[0:3]
print(array3)
print(type(array3))

In [ ]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

# ***NumPy Indexing PRACTICE***

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
'''1. 단일값 추출

[output]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
index 가리키는 값: 1
index 가리키는 값: 2
index 가리키는 값: 4
index 가리키는 값: 9

'''


array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

'''2. Slicing

[output]

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

(1)
array2d:
 [[1 2]
 [4 5]]

 (2)
array2d:
 [[2 3]
 [5 6]]

 (3)
array2d:
 [1 4]

# (3) array2d shape: (2,)
'''

* fancy indexing

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

print(array2d)
array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3)

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4)

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5)

# 행렬의 정렬 – sort( )와 argsort( )
* 행렬 정렬

In [ ]:
org_array = np.array([ 3, 1, 9, 5])
print('원본 행렬:', org_array)
# np.sort( )로 정렬
sort_array1 = np.sort(org_array)
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort( ) 호출 후 원본 행렬:', org_array)
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc)

In [ ]:
array2d = np.array([[8, 12],
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

* 정렬 행렬의 인덱스 반환

In [ ]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

In [ ]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

# ***NumPy sort() PRACTICE***

In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

'''practice
[output]

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']

'''

## 선형대수 연산 – 행렬 내적과 전치 행렬 구하기
* 행렬 내적

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
print(A.shape)
print(B.shape)
dot_product = np.dot(A, B)

print('행렬 내적 결과:\n', dot_product)

* 전치 행렬

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

# Pandas

In [ ]:
import pandas as pd

data = {'Name': ["John", "Anna", "Peter", "Linda"],
        'Location' : ["New York", "Paris", "Berlin", "London"],
        'Age' : [24, 13, 53, 33]
       }

data_pandas = pd.DataFrame(data)

data_pandas

In [ ]:
# Age 열의 값이 30 이상인 모든 행을 선택합니다.
data_pandas[data_pandas.Age > 30]

* DataFrame 데이터 삭제

In [ ]:
data = {'Name': ["John", "Anna", "Peter", "Linda"],
        'Location' : ["New York", "Paris", "Berlin", "London"],
        'Age' : [24, 13, 53, 33]
       }

data_pandas = pd.DataFrame(data)

In [ ]:
data_drop = data_pandas.drop('Age', axis = 1)
data_drop

# DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환
* numpy ndarray, list, dictionary를 DataFrame으로 변환하기

In [ ]:
col_name1=['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)
print('array1 shape:', array1.shape )

# 리스트를 이용해 DataFrame 생성.
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)

# 넘파이 ndarray를 이용해 DataFrame 생성.
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

In [ ]:
# 3개의 칼럼명이 필요함.
col_name2=['col1', 'col2', 'col3']

# 2행x3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환.
list2 = [[1, 2, 3],
         [11, 12, 13]]
array2 = np.array(list2)
print('array2 shape:', array2.shape )
df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
df_array2 = pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

In [ ]:
# Key는 컬럼명으로 매핑, Value는 리스트 형(또는 ndarray)
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

* DataFrame을 넘파이 ndarray, 리스트, 딕셔너리로 변환하기

In [ ]:
# DataFrame을 ndarray로 변환
array3 = df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.values shape:', array3.shape)
print(array3)

In [ ]:
# DataFrame을 리스트로 변환
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
print(list3)

# DataFrame을 딕셔너리로 변환
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입:', type(dict3))
print(dict3)